### PR TITLE
Merged changes into dev

### PR DESCRIPTION
**Pull request by DominicVonk**

### CODE REVIEW

**Comment by robertgr991** [comment]
I've merged this into `dev`, as I said the php parser returns a different number of params in some cases, I have to look into this before I update the version.

**Comment by DominicVonk** [comment]
Sure, can you make the tests available?

**Comment by robertgr991** [comment]
They are not really tests, just some random files from some of my previous projects. I will try to make some test files later this week. Btw, I published a new version with your fix for the regex that parses the phpdoc, thanks.

**Comment by DominicVonk** [comment]
Sure, could you send me a file were things go wrong? Because I tested it with several projects, and it works for all of them. (Zend Framework 1, Laravel 7, Plain PHP)

**Pull request merged**
